### ISSUE TITLE
Test installation for various Linux distributions

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1147]
We've not tested [installation guide for Linux](https://ebiten.org/documents/install.html?os=linux) very well, and we have found some issues (e.g., https://github.com/hajimehoshi/ebiten/issues/1146).

To solve this, we can have Docker files for various distributions, and test them regularly.

**Comment by hajimehoshi** [comment]
So the action items are make Docker files for various Linux distribution that installs Ebiten and run go-test, and add the Docker files to Ebiten repository (/docker directory, maybe?)

Contributions are welcome!

**Comment by beoran** [comment]
Let me look into it for a whle an see if I can help. I am a Linux user after all. :)

**Comment by hajimehoshi** [comment]
Thanks!

**Comment by notxarb** [comment]
I have some experience with Dockerfiles, I can help too.

**Comment by nanoslayer** [comment]
Here are the dependencies needed for Alpine Linux:

```
apk add go alsa-lib-dev libx11-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev mesa-dev
```

I used [sourcehut builds](https://builds.sr.ht) to test building Ebiten on Alpine Linux. It also supports Arch, Fedora, and Ubuntu, among [others](https://man.sr.ht/builds.sr.ht/compatibility.md). It can also integrate with your Github repositories. If you like I can work on adding build manifests to the repo.

**Comment by hajimehoshi** [comment]
Cool! Would it be possible to make the Dockerfile work on GitHub actions?

**Comment by nanoslayer** [comment]
I managed to get Ebiten to pass all tests on Alpine Linux!

Here is the build manifest:

```yml
image: alpine/latest
packages:
  - alsa-lib-dev
  - libx11-dev
  - libxrandr-dev
  - libxcursor-dev
  - libxinerama-dev
  - libxi-dev
  - mesa-dev
  - mesa-dri-intel
  - go
  - xvfb-run
sources:
  - https://github.com/hajimehoshi/ebiten
tasks:
  - test: |
      cd ebiten
      xvfb-run go test -v
```

I will open a pull request.
