### ISSUE TITLE
Use Docker at GitHub Actions instead of build.sh.ht

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1664]
Apparently build.sh.ht accepts only 4 VMs at one commit. Use Dockers on GitHub actions instead.

**Comment by hajimehoshi** [comment]
We can still rely on build.sh.ht for FreeBSD.

**Comment by hajimehoshi** [comment]
Creating a Dockerfile is not an easy task:

```yaml
name: linux

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        image: ['debian:latest', 'ubuntu:latest']
    name: Test with ${{ matrix.image }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    env:
      DISPLAY: ':99.0'
      DEBIAN_FRONTEND: noninteractive
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'

      - name: Install dependencies
        if: ${{ matrix.image == 'debian:latest' || matrix.image == 'ubuntu:latest' }}
        run: |
          apt-get update
          apt-get install -y libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev pkg-config                                                                                                                                          

      - name: Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: go test
        run: |
          go test -tags=example -v ./...
```

This seems to work, but actually doesn't due to a certification error.

Can we use [the API](https://man.sr.ht/builds.sr.ht/api.md) from GitHub Actions instead of Webhooks?
